CodEval.Web/Controllers/HomeController.cs
using CodEval.BLL.Services;
using CodEval.Web.Helpers;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CodEval.BLL.Models;
using CodEval.DAL.Repository;
using System.IO;
using System.Data.Entity;

namespace CodEval.Web.Controllers
{
    [Authenticated]
    public class HomeController : Controller
    {
        private ContestsService _contestsService;
        private ProblemsService _problemsService;

        public HomeController()
            : this(new CodEvalEntities())
        {
        }

        public HomeController(DbContext context)
        {
            _contestsService = new ContestsService(context);
            _problemsService = new ProblemsService(context);            
        }

        #region Contests

        public ActionResult Index(int? contestId)
        {
            if (contestId.HasValue)
            {
                ViewBag.ContestName = _contestsService.GetContestNameById(contestId.Value);
                ViewBag.IsActiveContest = _contestsService.IsActiveContest(contestId.Value);
                ViewBag.RemainingTime = _contestsService.GetContestRemainingTime(contestId.Value);
                ViewBag.AcceptedProgrammingLanguages = _contestsService.GetContestProgrammingLanguages(contestId.Value);
                ViewBag.ContestDescription = _contestsService.GetContestDescription(contestId.Value);
            }
            return View(contestId);
        }        

        public ActionResult GetContests([DataSourceRequest] DataSourceRequest request)
        {
            return Json(_contestsService.GetAllContests().ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }        

        public ActionResult GetProblems([DataSourceRequest] DataSourceRequest request, int contestId)
        {
            if (SessionHelper.CurrentContestant != null)
            {
                return Json(_problemsService.GetContestProblems(SessionHelper.CurrentContestant.ID, contestId).ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            }
            return Json((new List<ProblemSubmission>()).ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }        
        
        #endregion        
    }
}

CodEval.Web/Controllers/ProblemController.cs
using CodEval.BLL.Services;
using CodEval.DAL.Repository;
using CodEval.Web.Helpers;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodEval.Web.Controllers
{
    [Authenticated]
    public class ProblemController : Controller
    {
        private ProblemsService _problemsService;

        public ProblemController()
            : this(new CodEvalEntities())
        {
        }

        public ProblemController(DbContext context)
        {
            _problemsService = new ProblemsService(context);
        }

        public ActionResult Index(int? id)
        {
            if (id.HasValue)
            {
                var problem = _problemsService.GetFullProblemDataById(id.Value);
                if (problem != null)
                {
                    if (problem.Contest.StartDate <= DateTime.Now)
                    {
                        return View(problem);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home", new { contestId = problem.Id_Contest });
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Review(ProblemReview review)
        {
            review.Id_Contestant = SessionHelper.CurrentContestant.ID;
            review.ReviewDate = DateTime.Now;
            _problemsService.AddProblemReview(review);
            return RedirectToAction("Index", new { id = review.Id_Problem });
        }
    }
}

CodEval.Web/Controllers/RankingController.cs
using CodEval.BLL.Models;
using CodEval.BLL.Services;
using CodEval.DAL.Repository;
using CodEval.Web.Helpers;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodEval.Web.Controllers
{
    [Authenticated]
    public class RankingController : Controller
    {
        private ContestsService _contestsService;
        
        public RankingController()
            : this(new CodEvalEntities())
        {
        }

        public RankingController(DbContext context)
        {
            _contestsService = new ContestsService(context);                        
        }

        public ActionResult Index(int? contestId)
        {
            if (!contestId.HasValue)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ContestName = _contestsService.GetContestNameById(contestId.Value);
            return View(contestId.Value);
        }

        public ActionResult GetRankings([DataSourceRequest] DataSourceRequest request, int contestId)
        {
            return Json(_contestsService.GetRankingsForContest(contestId).ToDataSourceResult(request));
        }
    }
}

CodEval.Web/Controllers/SubmissionsController.cs
using CodEval.BLL.Models;
using CodEval.BLL.Services;
using CodEval.Web.Helpers;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CodEval.DAL.Repository;
using System.IO;

namespace CodEval.Web.Controllers
{
    [Authenticated]
    public class SubmissionsController : Controller
    {
        private static string _submissionsFolder = System.Web.HttpContext.Current.Server.MapPath("~/App_Data/Submissions/");

        private ContestsService _contestsService;
        private ProblemsService _problemsService;
        private TestsService _testsService;

        public SubmissionsController()
            : this(new CodEvalEntities())
        {
        }

        public SubmissionsController(DbContext context)
        {
            _contestsService = new ContestsService(context);
            _problemsService = new ProblemsService(context);
            _testsService = new TestsService(context, String.Empty);
        }

        public ActionResult Index(int? id)
        {
            if (id.HasValue)
            {
                Submission submission;
                if (SessionHelper.CurrentAdmin != null)
                {
                    submission = _contestsService.GetSubmissionById(id.Value);
                }
                else
                {
                    submission = _contestsService.GetContestantSubmission(SessionHelper.CurrentContestant.ID, id.Value);
                }                 
                if (submission != null)
                {
                    var submissionSourceCode = _contestsService.GetContestantSubmissionSourceCode(submission.ID_Contestant, id.Value, _submissionsFolder);
                    ViewBag.Submission = submission;
                    ViewBag.SubmissionSourceCode = submissionSourceCode;
                    ViewData["tests"] = _testsService.GetTestsNamesForProblem(submission.ID_Problem);
                    ViewData["statuses"] = _testsService.GetAllStatusesNames();
                    return View(id);
                }
                return RedirectToAction("Index");
            }
            else
            {
                var problem_contest = _contestsService.GetAllProblem_ContestsNames();
                var submissionsStatuses = _contestsService.GetAllSubmissionsStatuses();
                List<SubmissionScore> submissionsScores;
                if (SessionHelper.CurrentAdmin != null)
                {
                    submissionsScores = _contestsService.GetSubmissionsScores();
                }
                else
                {
                    submissionsScores = _contestsService.GetContestantSubmissionsScores(SessionHelper.CurrentContestant.ID);
                }
                ViewData["problem_contest"] = problem_contest;
                ViewData["submissionsStatuses"] = submissionsStatuses;
                ViewData["submissionsScores"] = submissionsScores;

                return View(id);
            }
        }

        public ActionResult GetSubmissions([DataSourceRequest] DataSourceRequest request)
        {
            return Json(_contestsService.GetContestantSubmissions(SessionHelper.CurrentContestant.ID).ToDataSourceResult(request));
        }

        public ActionResult GetSubmissionResults([DataSourceRequest] DataSourceRequest request, int submissionId)
        {
            if (SessionHelper.CurrentAdmin != null)
            {
                return Json(_contestsService.GetSubmissionResults(submissionId).ToDataSourceResult(request));
            }
            else
            {
                return Json(_contestsService.GetSubmissionResults(SessionHelper.CurrentContestant.ID, submissionId).ToDataSourceResult(request));
            }            
        }

        [HttpPost]
        public ActionResult Submit(HttpPostedFileBase file, int problemId)
        {
            var problem = _problemsService.GetProblemById(problemId);
            if (problem != null)
            {
                if (_contestsService.IsValidSubmission(problemId, file.FileName, file.ContentLength))
                {
                    var destinationFolder = _submissionsFolder + problem.Id_Contest + "/" + SessionHelper.CurrentContestant.Username;
                    bool status = _contestsService.AddSubmission(problemId, SessionHelper.CurrentContestant.ID, destinationFolder, file.FileName.ToLower(), file.InputStream);
                    if (status)
                    {
                        return Json(new { OK = true, Message = "Submitted!" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { OK = false, Message = "An unexpected error occured, please try again!" }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { OK = false, Message = "Invalid submission file!" }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { OK = false, Message = "Invalid problem!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

CodEval.Web/Views/Home/Index.cshtml
@model int?
@{
    ViewBag.Title = "CodEval " + DateTime.Now.Year;    
}
@{
    if (Model.HasValue)
    {
        @Html.Partial("_ContestPartial", Model.Value)        
    }
    else
    {
        @Html.Partial("_ContestsListPartial")    
    }
}

CodEval.Web/Views/Home/_ContestPartial.cshtml
@model int
@{
    var acceptedProgrammingLanguages = ViewBag.AcceptedProgrammingLanguages as List<CodEval.DAL.Repository.ProgrammingLanguage>;
}
<h2>@ViewBag.ContestName</h2>
@(Html.Kendo().Grid<CodEval.BLL.Models.ProblemSubmission>()
                .Name("problemsGrid")
                .Columns(columns =>
                {
                    columns.Bound(e => e.ProblemName).ClientTemplate("<a href=\"" + Url.Action("Index", "Problem") + "?id=#=ProblemId#\">#=ProblemName#</a>");
                    columns.Bound(e => e.SolutionName).ClientTemplate("<a href=\"" + Url.Action("Index", "Submissions") + "?id=#=SubmissionId#\" target=\"_blank\">#=SolutionName#</a>");
                    columns.Bound(e => e.AcceptedTime).Format("{0:dd-MM-yyyy HH:mm:ss}");
                    columns.Bound(e => e.ProblemId).Width(200).Visible(false).Title("Submission").ClientTemplate("<div class=\"uploadFilesClass\"><input name=\"files\" id=\"upload_#=ProblemId#\" type=\"file\" data-prid=\"#=ProblemId#\" /></div>");
                })
                .DataSource(dataSource => dataSource
                    .Ajax()
                    .Read(read => read.Action("GetProblems", "Home", new { contestId = Model }))
                 )
                 .AutoBind(true)
                 .Events(e => e.DataBound("onProblemsGridDataBound"))
            )
@if ((bool)ViewBag.IsActiveContest)
{
    var remainingTime = (TimeSpan)ViewBag.RemainingTime;
    <h3 style="color: red;">@ViewBag.ContestName ends in @String.Format(@"{0:%d} days, {0:hh\:mm\:ss}", remainingTime)</h3>
}
else
{
    <h3 style="color: red;">@ViewBag.ContestName isn't active now!</h3>
}
@if (!String.IsNullOrWhiteSpace(ViewBag.ContestDescription))
{
    <h3>Description:</h3>
    <p id="description">
        @Html.Raw(ViewBag.ContestDescription)
    </p>
}
@if (acceptedProgrammingLanguages.Any())
{
    <h3>Accepted Programming Languages:</h3>
    <ul>
        @foreach (var lang in acceptedProgrammingLanguages)
        {
            <li>
                @lang.Name
            </li>
        }
    </ul>
}

<script>
    function onProblemsGridDataBound() {
        $.each($('.uploadFilesClass'), function () {
            var grid = $('#problemsGrid').data().kendoGrid;
            var row = $(this).closest('tr');
            var dataItem = grid.dataItem(row);
            $("#upload_" + dataItem.ProblemId).kendoUpload({
                multiple: false,
                async: {
                    saveUrl: "@Url.Action("SubmitSubmission", "Submissions")",
                    autoUpload: true
                },
                upload: onUpload,
                success: onSubmitSuccess,
                error: onSubmitError,
                select: onSelect
            });
        });
    }

    function onUpload(e) {
        e.data = {
            problemId: e.sender.element.data('prid')
        };
    }

    function onSelect(e) {
        $.each(e.files, function (index, value) {
            //value.name
            if (!(value.size < 20480 && (value.extension.toLowerCase() == '.pas' || value.extension.toLowerCase() == '.cpp' || value.extension.toLowerCase() == '.c'))) {
                e.preventDefault();
                alert('Invalid File!');
            }
        });
    };

    function onSubmitSuccess(e) {
        alert('Submission succeded!');
        $('#problemsGrid').data('kendoGrid').dataSource.read();
    }

    function onSubmitError(e) {
        alert(e.XMLHttpRequest.responseText);
    }
</script>

CodEval.Web/Views/Home/_ContestsListPartial.cshtml
<h2>Contests</h2>
@(Html.Kendo().Grid<CodEval.DAL.Repository.Contest>()
            .Name("contestsGrid")
            .Columns(columns =>
            {
                columns.Bound(e => e.Name).ClientTemplate("<a href=\"" + Url.Action("Index", "Home") + "?contestId=#=ID#\">#=Name#</a>");
                columns.Bound(e => e.StartDate).Format("{0:dd-MM-yyyy HH:mm}");
                columns.Bound(e => e.EndDate).Format("{0:dd-MM-yyyy HH:mm}");
                columns.Bound(e => e.Id_Admin).Visible(false).Title("Problems").ClientTemplate("<a href=\"" + Url.Action("Index", "Home") + "?contestId=#=ID#\">Problems</a>");
                columns.Bound(e => e.Id_Admin).Title("Rankings").ClientTemplate("<a href=\"" + Url.Action("Index", "Ranking") + "?contestId=#=ID#\">Rankings</a>").Filterable(false);
            })
            .Filterable()
            .Pageable()
            .Navigatable()
            .Sortable()
            .Scrollable()
            .AutoBind(true)
            .DataSource(dataSource => dataSource
                .Ajax()
                .Batch(true)
                .PageSize(50)
                .ServerOperation(false)
                .Events(events => events.Error("error_handler"))
                .Model(model =>
                {
                    model.Id(p => p.ID);
                    model.Field(p => p.Name).Editable(false);
                    model.Field(p => p.StartDate).Editable(false);
                    model.Field(p => p.EndDate).Editable(false);
                    model.Field(p => p.Id_Admin).Editable(false);
                }
                )
                .Read("GetContests", "Home")
            )
        )
<script type="text/javascript">
    function error_handler(e) {
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });
            alert(message);
        }
    }
</script>